version: '3'

services:
#  db:
#    image: postgres
  server:
    build: .
    command: python manage.py runserver 0.0.0.0:7114
    volumes:
      - .:/code
    ports:
      - "7114:7114"
#    depends_on:
#      - db